### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by LisaHollstein** [MHH-RCUG/nf_wochenende#13]
Hi @colindaven,

I have some trouble installing Wochenende at a server without SLURM. The only Server that I can even start a ssh session on seems to be hpc08, but this server doesn't have bioconda installed and I don't think I have the rights to do this. Who should I contact regarding this? Are Torsten and Maike responsible or do I need to contact someone else? Or am I missing something and I should be able to do this on my own?

**Comment by colindaven** [comment]
Rights are all in the user space for bioconda, so you should be able to install (via miniconda 64 bit). Are you using the rcug_lw account as usual? 
Also the bc15 servers should have accounts and permissions set so you can install miniconda with no problems. Maybe try bc15-05 ? Maike should be able to troubleshoot with you as well, sure.

**Comment by LisaHollstein** [comment]
Thanks,  bc15-05 doesn't work (session won't start), but I the installation on hpc08 worked well

**Comment by LisaHollstein** [comment]
@kosankem the nextflow installation requires java (any version between java 11 and 18), which is not installed on hpc08, could you install that for me?

**Comment by colindaven** [comment]
@LisaHollstein you can install via miniconda2, try following the nf_wochenende Wiki Install instructions (with the minimal env from the dev branch at present, it contains java and nextflow).

**Comment by kosankem** [comment]
Hallo @LisaHollstein,  
Do you need it in a conda environment or really on a specific server? Conda I can do, for the other one you need to ask the server admin.

**Comment by LisaHollstein** [comment]
@colindaven Okay, then maybe the Wiki needs some changes, because step 2 states, that nextflow should be installed as described here: https://www.nextflow.io/docs/latest/getstarted.html#installation

**Comment by colindaven** [comment]
Yes, good point, it just changed this morning :-)

**Comment by colindaven** [comment]
Yes, I could download the files from home too. Many workplace firewalls block filesharing sites as well, but we can't deal with all endpoints.
