### ISSUE TITLE
updating docs etc 

### ISSUE THREAD

**Issue by colindaven** [MHH-RCUG/nf_wochenende#16]
Hi @irosenboom 

thanks for the new pics.

Can you please upload them to this repo, not the Wochenende repo, and use the dev branch so they don't get overwritten ?

link:
https://github.com/MHH-RCUG/nf_wochenende/tree/dev

Thanks.
Colin

**Comment by irosenboom** [comment]
Hi @colindaven 
yes sure, I will add them here as well. Should I also add output for growth rate and raspir?
