### ISSUE TITLE
flagstat.txt and postprocess

### ISSUE THREAD

**Issue by LisaHollstein** [MHH-RCUG/nf_wochenende#24]
Hi @colindaven,

I noticed that no `flagstat.txt` are created when running nf_wochenende. I don't think there is any problem on my side regarding this. Is this on purpose?

**Comment by colindaven** [comment]
Hi @LisaHollstein 
it's just for alignment statistics, and not critical, so can be corrected later if it is a problem.
cheers,
Colin

**Comment by LisaHollstein** [comment]
@colindaven 
This also seems to be already in `nf_wochenende.nf` but is commented out.

Should this be done in `nf_wochenende.nf` or in the postprocess? (Would be no problem in the postprocess, I think, I just need to know where it should be done)

I am right now writing a nextflow postprocess script that contains all the postprocess steps, that are also in `wochenende_postprocess.sh`.

**Comment by colindaven** [comment]
That's a good question.Try uncommenting `flagstat` in the `nf_wochenende.nf` and see if throws an error ? Not sure why it's commented out right now.

Regarding postprocess - actually, I was planning to have all the steps in the `nf_wochenende.nf` unless you see a reason not to do so.

If you have a look at it, the stages 
- wochenende
- plots
are being used so far, and `plots` is part of `postprocess`. `Multiqc` might be used in the future. The others (sort bam etc) are just examples.

Don't you think it would be simplest to have it all in the one pipeline ? That would be the nextflow standard approach from what I have seen.

Perhaps, for ease of development, it might be ok to have your stages in a different file, eg `postprocess.nf` ? But then we have extra  work putting it all back together, and testing? I'll leave this decision to you though.

**Comment by LisaHollstein** [comment]
I think for development it is a bit easier for me to have a different file (and it is also faster when I test it). I don't think there will be a lot of problems when putting it back together.
