### ISSUE TITLE
remove setup.sh

### ISSUE THREAD

**Issue by colindaven** [MHH-RCUG/nf_wochenende#26]
Hi @LisaHollstein 

I'd like to remove `setup.sh` since we should be using variables / setup paths from within nextflow.config now. 

This also implies we shouldn't have anything related to Wochenende/ haybaler set within our .bashrc files. Please remove this on your test server.

I'll remove `setup.sh ` for now.

Thanks

**Comment by LisaHollstein** [comment]
Okay, but all the paths from the `config.yml` aren't in the `nextflow.config` right now

**Comment by LisaHollstein** [comment]
Which one do you think is cleaner?

**Comment by colindaven** [comment]
The first option , sorry formatting fail ..

**Comment by LisaHollstein** [comment]
`run_Wochenende.py` needs a few changes, especially because of the adapter paths, that are now set in `config.yml`. But it should be worth it

**Comment by colindaven** [comment]
Yes. V true. Need to generate a new test reference with a few species, and use the mock data, so I can properly test growth_rate and plots modules. But at a conference too so difficult right now
