### ISSUE TITLE
at work

### ISSUE THREAD

**Issue by LisaHollstein** [MHH-RCUG/nf_wochenende#41]
Hi @colindaven,

I just wanted to let you now that I am at work for the next three days, so I will be able to contribute to `nf_wochenende`

**Comment by colindaven** [comment]
Let me know if you have issues - the path to the `perldup` program changed especially in the config, so make sure you update your config and manually compare the configs (I removed or commented out lots of stuff) between the branches lisa-dev and colin_dev.

I generally avoided your sections but removed the dependency on `ref.tmp` files for the `reporting` step.

Let me know if you have issues, hope it works ok for you. 

Pls see status : https://github.com/MHH-RCUG/nf_wochenende/issues/38
