### ISSUE TITLE
Wochenende Plot .png output

### ISSUE THREAD

**Issue by irosenboom** [MHH-RCUG/nf_wochenende#43]
TODO: optimize Wochenende Plot output
- [x]  change white bar for Mean Coverage to red bar
- [x]  add example with low coverage and non-uniform read distribution

**Comment by colindaven** [comment]
@irosenboom Better  ? I think so.

https://github.com/MHH-RCUG/nf_wochenende/blob/colin_dev/dependencies/1_AE004091_2_Pseudomonas_aeruginosa_PAO1__BAC_0_red.png

**Comment by colindaven** [comment]
@irosenboom and more pics. 

Note Bacillus intestinalis is heavily present and completely covered (this it the 2021_12 ref). We should definitely include this image in the supplement (or part of Fig 2, the comparison pic?) and state that B. subtilis is definitely not present yet B. intestinalis is there in the Zymo mock.

https://github.com/MHH-RCUG/nf_wochenende/tree/colin_dev/dependencies

**Comment by irosenboom** [comment]
@colindaven the plot is now much easier to understand, perfect!

I will definitely include the Bacillus intestinalis plot in the supplement, so that we can stress our assumption about the Zymo mock.
