### ISSUE TITLE
handing over parameters

### ISSUE THREAD

**Issue by colindaven** [MHH-RCUG/nf_wochenende#47]
Hi @LisaHollstein 

I don't think this is working well yet, since nextflow/groovy does not overwrite parameters:

I had this while testing on batches of newer data in my branch colin_dev

```
WARN: `params.mq` is defined multiple times -- Assignments following the first are ignored
WARN: `params.mq` is defined multiple times -- Assignments following the first are ignored
WARN: `params.no_duplicate_removal` is defined multiple times -- Assignments following the first are ignored
WARN: `params.abra` is defined multiple times -- Assignments following the first are ignored
WARN: `params.abra` is defined multiple times -- Assignments following the first are ignored
WARN: `params.abra` is defined multiple times -- Assignments following the first are ignored
WARN: `params.abra` is defined multiple times -- Assignments following the first are ignored
WARN: `params.abra` is defined multiple times -- Assignments following the first are ignored
WARN: `params.abra` is defined multiple times -- Assignments following the first are ignored
WARN: `params.abra` is defined multiple times -- Assignments following the first are ignored
WARN: `params.no_duplicate_removal` is defined multiple times -- Assignments following the first are ignored
WARN: `params.abra` is defined multiple times -- Assignments following the first are ignored
WARN: `params.abra` is defined multiple times -- Assignments following the first are ignored
WARN: `params.abra` is defined multiple times -- Assignments following the first are ignored
WARN: `params.abra` is defined multiple times -- Assignments following the first are ignored
WARN: `params.prinseq` is defined multiple times -- Assignments following the first are ignored
WARN: `params.no_duplicate_removal` is defined multiple times -- Assignments following the first are ignored
WARN: `params.no_duplicate_removal` is defined multiple times -- Assignments following the first are ignored
WARN: `params.no_duplicate_removal` is defined multiple times -- Assignments following the first are ignored
WARN: `params.prinseq` is defined multiple times -- Assignments following the first are ignored
WARN: `params.no_duplicate_removal` is defined multiple times -- Assignments following the first are ignored
WARN: `params.no_duplicate_removal` is defined multiple times -- Assignments following the first are ignored
WARN: `params.no_duplicate_removal` is defined multiple times -- Assignments following the first are ignored
WARN: `params.no_duplicate_removal` is defined multiple times -- Assignments following the first are ignored
WARN: `params.prinseq` is defined multiple times -- Assignments following the first are ignored
WARN: `params.no_duplicate_removal` is defined multiple times -- Assignments following the first are ignored
WARN: `params.no_duplicate_removal` is defined multiple times -- Assignments following the first are ignored
WARN: `params.no_duplicate_removal` is defined multiple times -- Assignments following the first are ignored
WARN: `params.no_duplicate_removal` is defined multiple times -- Assignments following the first are ignored
WARN: `params.prinseq` is defined multiple times -- Assignments following the first are ignored
WARN: `params.prinseq` is defined multiple times -- Assignments following the first are ignored
WARN: `params.prinseq` is defined multiple times -- Assignments following the first are ignored

```

**Comment by LisaHollstein** [comment]
Those are assigned multiple times in the script, but only once when the script is running because the assingments are in if ... else statements, e.g.:

```
 if (params.no_prinseq) {
       params.prinseq = "--no_prinseq"
    } else {
       params.prinseq = ""
    }
```

So I think it works, although it is obviously not pretty that we always have these warnings.

**Comment by colindaven** [comment]
Ok, thanks! However, I think having these warnings is bad practice and incorrect, since only the first assignment actually counts, others are ignored.

>  Assignments following the first are ignored


I think we need to deal with the parameters differently for another reason, namely that `true` is passed on by bash (or groovy, not sure) to the python script, which only respects `True` (capital letter!) as a boolean. This leads to many options failing.

In more detail, last night I was checking options for long reads and I found `--longread` wasn't working (trimming, which is only for short reads, was activated). 

The solution is not complete and tested at all, but have a look at the last commit in `colin_dev` branch https://github.com/MHH-RCUG/nf_wochenende/commit/d30dc39c4d95fb4ce47f746e61ec506d80e8e869

and in particular see the whole of the `nextflow.config`.

I think this will allow us to remove all our troubles with parameters by using this config file only. But it's only 50% done and not tested broadly yet. 

Please have a look at the pull requests from `dev-> main` and from `colin_dev to dev` when you get a chance. 

Thanks!

**Comment by LisaHollstein** [comment]
Setting all the parameters in the `nextflow.config` seems like a great idea! I will test it

**Comment by colindaven** [comment]
The bash to groovy to python inconsistencies become even worse than just true / True mismatches.

I had already found out that no bash variables should be used as **empty strings evaluate to true in groovy**. So yes, lets' try to avoid setting anything via bash variables, and just use the `nextflow.config`.

This would explain again why we had so many issues with the config.

**Comment by LisaHollstein** [comment]
Oh, okay. I will change the variables for the parts that I have written

**Comment by colindaven** [comment]
Please check the current commits in colin_dev from today, I changed quite a lot already

**Comment by colindaven** [comment]
resolved
