### ISSUE TITLE
Running nf_wochenende with fastp

### ISSUE THREAD

**Issue by irosenboom** [MHH-RCUG/nf_wochenende#84]
Hi @colindaven , I want to use fastp instead of trimmomatic (we are again working on the high number of species problem). However, nextflow reported the following error:

```
Command error:
  Traceback (most recent call last):
    File "run_Wochenende.py", line 1792, in <module>
      main(parser.parse_args(), sys.argv[1:])
    File "run_Wochenende.py", line 1545, in main
      args.threads,
    File "run_Wochenende.py", line 243, in runFunc
      cF = func(cF, *extraArgs)
  TypeError: runFastpPE() missing 1 required positional argument: 'adapter_path'
```

Do we need to specify an additional `adapter_path` in `run_Wochenende.py` ? I can find a path for `args.nextera` in line 1422, but it seems like an option for `args.fastp` is missing.

**Comment by colindaven** [comment]
Hi @irosenboom , thanks for the bug report. I'll have a look at this later on. To be fair, I haven't tested fastp so far in the new version, but it's worth trying as its by far the fastest and newest adapter trimmer for Illumina reads.

**Comment by colindaven** [comment]
I solved some issues, but also changed the paths to the adapters in the config.yaml file. You'll need to uncomment your fastp paths so fastp can find the adapters.

Please test the main branch, thanks!

**Comment by irosenboom** [comment]
It runs perfectly now, thanks!
